### ISSUE TITLE
Swiping with mouse selects background

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#47]
When swiping with the mouse (basically dragging), it seems the event propagates to the background file list and a lot of text gets selected.

@felixheidecke in case you have a quick fix

**Comment by PVince81** [comment]
solved in 1.0.0RC1

**Comment by skshetry** [comment]
I can still reproduce this in firefox v66, though didn't have any issues in `Chrome v73`, but I have to drag the video itself. This does not happen when the image is dragged, or dragged from the gray shadow, just the video.

![video2](https://user-images.githubusercontent.com/18718008/57059725-45b80600-6cd6-11e9-87cb-4b1a7bb09d5e.gif)
